# Generated by Django 5.2.7 on 2025-11-14 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
        ('posts', '0002_postflag'),
    ]

    operations = [
    ]
