# Generated by Django 5.2.7 on 2025-11-16 03:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_merge_0002_post_image_0002_postflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_hash',
            field=models.CharField(default=uuid.uuid4, max_length=10),
        ),
    ]
