# Generated by Django 5.2.7 on 2025-11-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_id_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_hash',
        ),
    ]
