# Generated by Django 5.2.7 on 2025-12-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_bookmark'),
        ('posts', '0009_post_status'),
    ]

    operations = [
    ]
