# Generated by Django 5.2.7 on 2025-10-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('hashed_email', models.CharField(max_length=10, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('picture_url', models.URLField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_new_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
            ],
            bases=('users.user',),
        ),
    ]
