# Generated by Django 5.2.7 on 2025-11-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture_url',
            new_name='picture',
        ),
    ]
