# Generated by Django 5.2.5 on 2025-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_walkthrough',
            field=models.BooleanField(default=False),
        ),
    ]
