"""
Django settings for a2_market project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

"""
Django settings for a2_market project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID')
if not GOOGLE_OAUTH_CLIENT_ID:
    raise ValueError(
        'GOOGLE_OAUTH_CLIENT_ID is missing.'
        'Have you put it in a file at a2_market/.env ?'
    )

# AWS S3 configuration (optional)
# These are read from the environment so views (like s3_presign) can
# access the bucket name and boto3 can pick up credentials from env.
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION', 'us-east-1')

SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# Core settings
# ------------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set this via env: heroku config:set SECRET_KEY=...
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-tdt_y_@xdnb04h##hvo5rrw7azyy(7aqq@^&a+58k$cnboy#*4",
)

# DEBUG from env (defaults True for local dev)
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

# Hosts / CSRF (configure these on Heroku if you want to restrict)
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")
_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

# ------------------------------------------------------------------------------
# Applications
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    'daphne',
    "a2_market",
    "about.apps.AboutConfig",
    "login.apps.LoginConfig",
    "market.apps.MarketConfig",
    "users.apps.UsersConfig",
    "posts.apps.PostsConfig",
    "messaging.apps.MessagingConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "taggit",
]

# If AWS bucket is configured, enable django-storages S3 backend so
# FileField/ImageField save to S3 automatically.
if AWS_STORAGE_BUCKET_NAME:
    # Add 'storages' app if available
    if 'storages' not in INSTALLED_APPS:
        INSTALLED_APPS.append('storages')

    # Use django-storages S3 backend
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_S3_REGION_NAME = AWS_DEFAULT_REGION or None
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    # Keep objects private by default (recommended). Use presigned GET URLs to serve.
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }

# ------------------------------------------------------------------------------
# Middleware (WhiteNoise added for static files on Heroku)
# ------------------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",   # <-- add this
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "a2_market.urls"
LOGIN_URL = '/login/'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "a2_market.wsgi.application"

#for da messaging
ASGI_APPLICATION = "a2_market.asgi.application"

# ------------------------------------------------------------------------------
# Database
# ------------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# If a DATABASE_URL is present (Heroku Postgres), use it.
# pip install dj-database-url
try:
    import dj_database_url  # type: ignore

    if os.getenv("DATABASE_URL"):
        DATABASES["default"] = dj_database_url.parse(
            os.environ["DATABASE_URL"], conn_max_age=600, ssl_require=True
        )
except ImportError:
    pass

# ------------------------------------------------------------------------------
# Password validation
# ------------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/New_York"
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)  <<< Heroku / collectstatic fixes
# ------------------------------------------------------------------------------

# URL where static files are served from
STATIC_URL = "/static/"

# Where 'collectstatic' puts the compiled static files
STATIC_ROOT = BASE_DIR / "staticfiles"

# (Optional) Where your source static assets live during development.
# Only include if the folder exists to avoid warnings.
if (BASE_DIR / "static").exists():
    STATICFILES_DIRS = [BASE_DIR / "static"]

# WhiteNoise storage: compressed & hashed filenames for better caching
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ------------------------------------------------------------------------------
# Security / Heroku proxy headers
# ------------------------------------------------------------------------------

# Honor X-Forwarded-Proto / HTTPS when behind Heroku’s router
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ------------------------------------------------------------------------------
# Default primary key field type
# ------------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------------------------------------
# (Optional legacy) django-heroku support if present
# ------------------------------------------------------------------------------

try:
    if "HEROKU" in os.environ:
        import django_heroku  # type: ignore

        django_heroku.settings(locals(), staticfiles=False)
except ImportError:
    pass
