from django.test import TestCase, Client
from django.contrib.auth.models import User as DjangoUser
from django.urls import reverse
from .models import Messaging, Notification, Group, GroupMessage
from users.models import User as ProfileUser

# Source / AI Citation
# Description: Tests for messaging and notifications
# AI Source: Generated with Claude on 2025-12-09.
#   Initial prompt: "Add additional methods to provide comprehensive testing of the messaging and notification system of our app."
# Notes: 8 of the following 24 tests were generated by the above AI source. However, this code was analyzed to ensure that the tests aligned with the functionality of our app

class MessagingModelTests(TestCase):
    """Test the Messaging model"""
    
    def setUp(self):
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
    
    def test_create_message(self):
        """Test creating a message between two users"""
        message = Messaging.objects.create(
            author=self.user1,
            recipient=self.user2,
            content="Hello, this is a test message"
        )
        self.assertEqual(message.author, self.user1)
        self.assertEqual(message.recipient, self.user2)
        self.assertEqual(message.content, "Hello, this is a test message")
        self.assertIsNotNone(message.created_at)
    
    def test_message_ordering(self):
        """Test that messages are ordered by created_at"""
        msg1 = Messaging.objects.create(
            author=self.user1,
            recipient=self.user2,
            content="First message"
        )
        msg2 = Messaging.objects.create(
            author=self.user2,
            recipient=self.user1,
            content="Second message"
        )
        messages = Messaging.objects.all().order_by("created_at")
        self.assertEqual(messages[0], msg1)
        self.assertEqual(messages[1], msg2)


class NotificationModelTests(TestCase):
    """Test the Notification model"""
    
    def setUp(self):
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
        self.message = Messaging.objects.create(
            author=self.user1,
            recipient=self.user2,
            content="Test message"
        )
    
    def test_create_notification(self):
        """Test creating a notification"""
        notification = Notification.objects.create(
            recipient=self.user2,
            message=self.message
        )
        self.assertEqual(notification.recipient, self.user2)
        self.assertEqual(notification.message, self.message)
        self.assertFalse(notification.is_read)
        self.assertIsNotNone(notification.created_at)
    
    def test_mark_notification_as_read(self):
        """Test marking a notification as read"""
        notification = Notification.objects.create(
            recipient=self.user2,
            message=self.message
        )
        self.assertFalse(notification.is_read)
        
        notification.is_read = True
        notification.save()
        
        self.assertTrue(notification.is_read)
    
    def test_unread_notification_count(self):
        """Test counting unread notifications"""
        Notification.objects.create(recipient=self.user2, message=self.message)
        
        msg2 = Messaging.objects.create(
            author=self.user1,
            recipient=self.user2,
            content="Another message"
        )
        Notification.objects.create(recipient=self.user2, message=msg2)
        
        unread_count = Notification.objects.filter(
            recipient=self.user2,
            is_read=False
        ).count()
        
        self.assertEqual(unread_count, 2)


class GroupModelTests(TestCase):
    """Test the Group model"""
    
    def setUp(self):
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
        self.user3 = DjangoUser.objects.create_user(
            username='user3@test.com',
            email='user3@test.com',
            password='testpass123'
        )
    
    def test_create_group(self):
        """Test creating a group"""
        group = Group.objects.create(name="Test Group")
        group.members.add(self.user1, self.user2, self.user3)
        
        self.assertEqual(group.name, "Test Group")
        self.assertEqual(group.members.count(), 3)
        self.assertIn(self.user1, group.members.all())
    
    def test_group_message(self):
        """Test creating a message in a group"""
        group = Group.objects.create(name="Test Group")
        group.members.add(self.user1, self.user2)
        
        group_message = GroupMessage.objects.create(
            group=group,
            author=self.user1,
            content="Hello group!"
        )
        
        self.assertEqual(group_message.group, group)
        self.assertEqual(group_message.author, self.user1)
        self.assertEqual(group_message.content, "Hello group!")
        self.assertIsNotNone(group_message.timestamp)


class ChatListViewTests(TestCase):
    """Test the chat list view"""
    
    def setUp(self):
        self.client = Client()
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
        # Create a message to establish a chat
        Messaging.objects.create(
            author=self.user1,
            recipient=self.user2,
            content="Test message"
        )
    
    def test_chat_list_requires_login(self):
        """Test that chat list redirects if not logged in"""
        response = self.client.get(reverse('messaging:chat-list'))
        self.assertEqual(response.status_code, 302)  # Redirect
        self.assertIn('/login/', response.url)


class ChatViewTests(TestCase):
    """Test the individual chat view"""
    
    def setUp(self):
        self.client = Client()
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
    
    def test_chat_view_requires_login(self):
        """Test that chat view redirects if not logged in"""
        response = self.client.get(
            reverse('messaging:chat', kwargs={'username': 'user2@test.com'})
        )
        self.assertEqual(response.status_code, 302)
        self.assertIn('/login/', response.url)
    
    def test_chat_view_404_for_nonexistent_user(self):
        """Test that chat view returns 404 for non-existent user"""
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        response = self.client.get(
            reverse('messaging:chat', kwargs={'username': 'nonexistent@test.com'})
        )
        self.assertEqual(response.status_code, 404)


class SendMessageTests(TestCase):
    """Test sending messages"""
    
    def setUp(self):
        self.client = Client()
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
    
    def test_send_message_requires_login(self):
        """Test that sending a message requires login"""
        response = self.client.post(
            reverse('messaging:send-message', kwargs={'username': 'user2@test.com'}),
            {'content': 'Test'}
        )
        self.assertEqual(response.status_code, 302)
        self.assertIn('/login/', response.url)
    
    def test_send_message_creates_message(self):
        """Test that sending a message creates a Messaging object"""
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        response = self.client.post(
            reverse('messaging:send-message', kwargs={'username': 'user2@test.com'}),
            {'content': 'Test message content'}
        )
        
        self.assertEqual(response.status_code, 302)  # Redirects after sending
        self.assertTrue(
            Messaging.objects.filter(
                author=self.user1,
                recipient=self.user2,
                content='Test message content'
            ).exists()
        )
    
    def test_send_message_creates_notification(self):
        """Test that sending a message creates a notification"""
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        self.client.post(
            reverse('messaging:send-message', kwargs={'username': 'user2@test.com'}),
            {'content': 'Test notification'}
        )
        
        self.assertTrue(
            Notification.objects.filter(
                recipient=self.user2,
                is_read=False
            ).exists()
        )
    
    def test_send_empty_message_does_nothing(self):
        """Test that empty messages are not created"""
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        initial_count = Messaging.objects.count()
        
        self.client.post(
            reverse('messaging:send-message', kwargs={'username': 'user2@test.com'}),
            {'content': '   '}  # Only whitespace
        )
        
        self.assertEqual(Messaging.objects.count(), initial_count)


class NotificationViewTests(TestCase):
    """Test the notifications view"""
    
    def setUp(self):
        self.client = Client()
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
        self.message = Messaging.objects.create(
            author=self.user1,
            recipient=self.user2,
            content="Test message"
        )
    
    def test_notifications_view_requires_login(self):
        """Test that notifications view redirects if not logged in"""
        response = self.client.get(reverse('messaging:notifications'))
        self.assertEqual(response.status_code, 302)
        self.assertIn('/login/', response.url)
    
    
    def test_mark_notification_as_read(self):
        """Test marking a notification as read"""
        notification = Notification.objects.create(
            recipient=self.user2,
            message=self.message
        )
        
        session = self.client.session
        session['user_data'] = {'email': 'user2@test.com', 'given_name': 'User2'}
        session.save()
        
        response = self.client.post(
            reverse('messaging:mark-read', kwargs={'notification_id': notification.id})
        )
        
        self.assertEqual(response.status_code, 302)
        notification.refresh_from_db()
        self.assertTrue(notification.is_read)
    
    def test_cannot_mark_others_notification_as_read(self):
        """Test that users can't mark other users' notifications as read"""
        notification = Notification.objects.create(
            recipient=self.user2,
            message=self.message
        )
        
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        response = self.client.post(
            reverse('messaging:mark-read', kwargs={'notification_id': notification.id})
        )
        
        self.assertEqual(response.status_code, 404)


class GroupChatViewTests(TestCase):
    """Test group chat functionality"""
    
    def setUp(self):
        self.client = Client()
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
        self.group = Group.objects.create(name="Test Group")
        self.group.members.add(self.user1, self.user2)
    
    def test_group_chat_requires_login(self):
        """Test that group chat requires login"""
        response = self.client.get(
            reverse('messaging:group-chat', kwargs={'group_id': self.group.id})
        )
        self.assertEqual(response.status_code, 302)
        self.assertIn('/login/', response.url)
    
    
    def test_non_member_cannot_access_group(self):
        """Test that non-members cannot access group chat"""
        user3 = DjangoUser.objects.create_user(
            username='user3@test.com',
            email='user3@test.com',
            password='testpass123'
        )
        
        session = self.client.session
        session['user_data'] = {'email': 'user3@test.com', 'given_name': 'User3'}
        session.save()
        
        response = self.client.get(
            reverse('messaging:group-chat', kwargs={'group_id': self.group.id})
        )
        self.assertEqual(response.status_code, 302)
        self.assertEqual(response.url, reverse('messaging:chat-list'))
    
    def test_send_group_message(self):
        """Test sending a message to a group"""
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        response = self.client.post(
            reverse('messaging:send-group-message', kwargs={'group_id': self.group.id}),
            {'content': 'Group message test'}
        )
        
        self.assertEqual(response.status_code, 302)
        self.assertTrue(
            GroupMessage.objects.filter(
                group=self.group,
                author=self.user1,
                content='Group message test'
            ).exists()
        )


class StartChatViewTests(TestCase):
    """Test the start chat functionality"""
    
    def setUp(self):
        self.client = Client()
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
        self.user3 = DjangoUser.objects.create_user(
            username='user3@test.com',
            email='user3@test.com',
            password='testpass123'
        )
    
    def test_start_chat_requires_login(self):
        """Test that start chat requires login"""
        response = self.client.get(reverse('messaging:start-chat'))
        self.assertEqual(response.status_code, 302)
        self.assertIn('/login/', response.url)
    
    def test_start_chat_displays_users(self):
        """Test that start chat displays available users"""
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        response = self.client.get(reverse('messaging:start-chat'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'user2@test.com')
        self.assertContains(response, 'user3@test.com')
        self.assertNotContains(response, 'user1@test.com')  # Current user shouldn't appear
    
    def test_start_individual_chat(self):
        """Test starting a chat with one user"""
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        response = self.client.post(
            reverse('messaging:start-chat'),
            {'members': [self.user2.id]}
        )
        
        self.assertEqual(response.status_code, 302)
        self.assertIn(f'/messaging/chat/{self.user2.username}/', response.url)
    
    def test_start_group_chat(self):
        """Test starting a group chat with multiple users"""
        session = self.client.session
        session['user_data'] = {'email': 'user1@test.com', 'given_name': 'User1'}
        session.save()
        
        response = self.client.post(
            reverse('messaging:start-chat'),
            {'members': [self.user2.id, self.user3.id]}
        )
        
        self.assertEqual(response.status_code, 302)
        self.assertIn('/messaging/group/', response.url)
        
        # Verify group was created
        group = Group.objects.last()
        self.assertEqual(group.members.count(), 3)
        self.assertIn(self.user1, group.members.all())
        self.assertIn(self.user2, group.members.all())
        self.assertIn(self.user3, group.members.all())


class ContextProcessorTests(TestCase):
    """Test the unread notification context processor"""
    
    def setUp(self):
        self.client = Client()
        self.user1 = DjangoUser.objects.create_user(
            username='user1@test.com',
            email='user1@test.com',
            password='testpass123'
        )
        self.user2 = DjangoUser.objects.create_user(
            username='user2@test.com',
            email='user2@test.com',
            password='testpass123'
        )
    